### PR TITLE
Windows build

### PR DESCRIPTION
**Pull request by GregBowyer**
This is mostly to get the build to well build

### CODE REVIEW

**Comment by Thetoxicarcade** [comment]
:( windows builds

**Comment by GregBowyer** [comment]
You having problems with the windows build?

**Comment by Thetoxicarcade** [comment]
@GregBowyer Well, from PyPi it doesn't seem to want to work. Give me a second, I'll check again.

**Comment by Thetoxicarcade** [comment]
```
Processing dependencies for congredi==0.0.2b0
Searching for pycld2>=0.31
Reading https://pypi.python.org/simple/pycld2/
Downloading https://pypi.python.org/packages/21/77/8525fe5f147bf2819c7c9942c717c4a79b83f8003da1a3847759fb560909/pycld2-0.31.tar.gz#md5=4949eaf68723300b3cc1c0324fa7b16d
Best match: pycld2 0.31
Processing pycld2-0.31.tar.gz
Writing c:\users\appveyor\appdata\local\temp\1\easy_install-hkbq84\pycld2-0.31\setup.cfg
Running pycld2-0.31\setup.py -q bdist_egg --dist-dir c:\users\appveyor\appdata\local\temp\1\easy_install-hkbq84\pycld2-0.31\egg-dist-tmp-mbnx78
cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9002 : ignoring unknown option '-m64'
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
cldutil.cc
c:\users\appveyor\appdata\local\temp\1\easy_install-hkbq84\pycld2-0.31\cld2\internal\../public/compact_lang_det.h(65) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
error: Setup script exited with error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

Has the windows build ever been merged? Should I just use your fork instead like I do for entropy?
`git+https://github.com/xBeAsTx/python-entropy@win_compatibility`

**Comment by GregBowyer** [comment]
Ah yeah use my fork. The pypi project is called cld2-cffi

**Pull request closed without merging**
